files:
  - source: /locale/en_GB/admin_patches.po
    translation: /locale/%locale_with_underscore%/admin_patches.po
  - source: /locale/en_GB/magicked_admin.po
    translation: /locale/%locale_with_underscore%/magicked_admin.export.po
  - source: /docs/steam_guide.txt
    translation: /locale/%locale_with_underscore%/docs/steam_guide.txt
  - source: README.md
    translation: /locale/%locale_with_underscore%/README.md
