files:
  - source: /locale/en_GB/LC_MESSAGES/admin_patches.po
    translation: /locale/%locale_with_underscore%/LC_MESSAGES/admin_patches.po
  - source: /locale/en_GB/LC_MESSAGES/magicked_admin.po
    translation: /locale/%locale_with_underscore%/LC_MESSAGES/magicked_admin.po
  - source: /docs/steam_guide.txt
    translation: /locale/%locale_with_underscore%/docs/steam_guide.txt
