language: python
python:
    - "3.7"

os:
    - linux

install:
    - pip install python-coveralls
    - pip install flake8
    - pip install pytest
    - pip install pytest-cov
    - pip install -r requirements.txt

script:
    - make test
after_success:
    - coveralls
